---
abstract: Generate a list of all primes less than or equal
author:
  - 'David Oswald <daoswald@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
  Inline::MakeMaker: 0.50
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Prime-FastSieve
no_index:
  directory:
    - t
    - inc
requires:
  Inline: 0.50
  Inline::C: 0.50
  Inline::CPP: 0.39
  perl: 5.006000
version: 0.08
