---
abstract: 'Generate a list of all primes less than or equal'
author:
  - 'David Oswald <daoswald@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
  Inline::MakeMaker: 0.45
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Prime-FastSieve
no_index:
  directory:
    - t
    - inc
requires:
  Inline: 0.44
  Inline::CPP: 0.34
version: 0.07
